version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.15.0
    container_name: es01
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=CXY3AQ6jIkLsm7xzG641
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk-net

  logstash:
    image: logstash:8.10.2
    container_name: logstash
    volumes:
      - /home/tsika/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elk-net
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.15.0
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elk-net
    depends_on:
      - elasticsearch

networks:
  elk-net:
    driver: bridge
